[Database]
DBMS=MSS
serverName=knowplus_nt
;dataBase=km_test_dev
dataBase=km_live
;database = km_mdc_train
UserID=MGR
DatabasePassword=MGR
LogId=MGR
LogPassword=MGR
AutoCommit=FALSE
Lock=

[Database_confirm]
DBMS=MSS
serverName=knowplus_nt
dataBase=msdb
UserID=MGR
DatabasePassword=MGR
LogId=MGR
LogPassword=MGR
AutoCommit=FALSE
Lock=

[Database3]
DBMS=MSS
database=MSDB
serverName=knowplus_nt

[Documenting]
sharefolder = c:\

[Application]
PostZoom=84
Idletime=0
dateformat=dd/mm/yyyy
custlogo=crmlogo.bmp
librarylist=project.pbd,ifcadw.pbd,ifcaw.pbd,cfd.pbd,cfw.pbd,gld.pbd,glw.pbd,modify.pbd,nested.pbd,patch.pbd,apde.pbd,apdr.pbd,apw.pbd,arde.pbd,ardr.pbd,arw.pbd,bqd.pbd,bqw.pbd,cbd.pbd,cbw.pbd,cfrpt.pbd,cmd.pbd,cmw.pbd,fad.pbd,faw.pbd,gld.pbd,glw.pbd,icde.pbd,icdr.pbd,icw.pbd,lmd.pbd,lmw.pbd,mmd.pbd,mmw.pbd,msd.pbd,msw.pbd,pld.pbd,plw.pbd,pmd.pbd,pmw.pbd,pnd.pbd,pnw.pbd,pod.pbd,pow.pbd,sod.pbd,sodr.pbd,sow.pbd,sowr.pbd
custcompany=IFCA Consulting Sdn. Bhd.
custaddress1=25 Jalan SS20/11, Damansara Utama, Petaling Jaya Selangor
SetDefaultLanguage=Y
DefaultAccess=N
projectusage=Y
Batchlimit=150
Admfees='FA'
Insfees='INS'
Ridingfee='RA'
Entryfees='FE'
Fine='FI'
BredComm='LB'
MRAFund=
MRAAdm=
SycesComm='SC'
WinningComm='WC'
WinningJockey='WJ'
WinningManager='WM'
WinningTrainer='WT'

//[Fonts]
font1=IFCAData,Arial,8,68
font2=IFCALab,Arial,8,68
font3=IFCARepData,Arial,10,68
font4=IFCARepLab,Arial,10,68
font5=IFCANarrow,ArialNarrow,8,68
remove1=font.family="0"
remove2=font.family="1"
remove3=font.family="2"
remove4=font.family="3"
remove5=font.family="4"
remove6=font.family="5"
remove7=font.pitch="0"
remove8=font.pitch="1"
remove10=font.pitch="2"

[Security]
BmpBrowser=c:\res\*.*
WavBrowser=c:\res\*.wav
RowCount=l
PicBrowser=c:\res\*.bmp

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
Log On Fail=p2.wav
Log On Successfully=chimes.wav
Sound Enable=0

[Color]
Frame_Back=16777215
Sheet_Back=15466495
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
Dw_Back=12632256
Column_Back=16777215

[SystemSettings]
//UseEntity=1
//ProjectUsage=1
//MenuStyle=TreeView
//MenuStyle=Explorer
MenuStyle=Web
ShowToolbarText=0
ResourcesLocation=c:\res

[UserSettings]
ApplicationLogo=knowledge_logo3.bmp
CompanyName=IFCA Software Co. Ltd.
CompanyAddress1=400 Orchard Road
CompanyAddress2=#15-06 Orchard Towers
CompanyAddress3=Singapore 238875
CompanyLogo=knowledge_main3.bmp

[Dashboard]
htmldirectory=C:\IFCA\DigitalDashboard

[CRMSettings]
GURL_Desktop=c:\res\html\
GURL_EMAIL=http://ecommerce/exchange/ 
GURL_LIBRARY=http://cyber-rey-2k/dev/
OUTLOOK_PATH="C:\Program Files\Microsoft Office\Office\OUTLOOK.EXE"  /recycle
GEMAIL_SERVER=EXCHANGE
//GEMAIL_SERVER=LOTUS_NOTES
GUSE_OUTLOOK=0
//GUSE_OUTLOOK=1 : Yes     GUSE_OUTLOOK=0 : No

[ReportWriter]
TemplateDir=C:\tempdir

[knowplus_nt]
license=8NK6L99H59G2CG6OQ4CQ28FB311IGA
accessreminder=2


[HP_NT]
license=88WQF22X58ZK3XDNEKQ28FB3M1IGAF
accessreminder=2

[Messages]
x=-18
y=-92
w=4699
h=2724

