[Database]             
Vendors=ODBC
DBMS=MSS
ServerName=SUPPORT_NT
Database=dtrain
//Database=olympia
//Database=panther
//Database=auto
//Database=RSGC
UserID=MGR
DatabasePassword=MGR
LogId=MGR
LogPassword=MGR
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
;DbParm=release='4.2'
AutoCommit=FALSE
Lock=

[Application]
Idletime=0
custlogo=bv.bmp
maxuserlicense=эюусзокЁ

[Security]
BmpBrowser=d:\res\*.bmp
WavBrowser=d:\res\*.wav
RowCount=l
//Bmp Brower=
//Wav Brower=d:\ifca\res\*.wav
//BmpBrower=d:\ifca\res\*.bmp
PicBrowser=
license=ю€цу№удЁв

[Membership]
PhotoBrowser=d:\dresort\photo\*.pho
signatureBrowser=d:\dresort\photo\*.sig

[Setup]
PhotoBrowser=d:\dresort\photo\*.pho


[Yacht]
ShipBrowser=d:\dresort\photo\*.shp

[Pier]
PierBrowser=d:\dresort\photo\*.yar

[Zone]
ZoneBrowser=d:\dresort\photo\*.zon

[Sound]
Enable=1
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
//Log On Fail=p2.wav
//Log On Successfully=chimes.wav
//Sound Enable=0

[Color]
Frame_Back=8421376
Sheet_Back=12845055
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
Dw_Back=12632256
Column_Back=16777215
