[Database]
DBMS=MSS
//Database=dhotel_demo
Database=dhotel_frontend
UserId=
DatabasePassword=
LogPassword=
//ServerName=ifca_pnts
//ServerName=ifca_nt_hotel
ServerName=crystal1_nt
LogId=""
Lock=
DbParm=
Prompt=0
//DbParm=ConnectString='DSN=dhotel_demo'
DbParm=ConnectString='DSN=dhotel_frontdesk'

[Database2]
//DBMS=MSS
//Database=dclub_demo
//ServerName=ifca_nt_hotel
//ServerName=crystal1_nt

[SystemSettings]
;MenuStyle=TreeView
MenuStyle=Explorer
MenuFontSize=8
MenuPictureSize=Default
ShowToolbarText=0
ResourcesLocation=d:\dhotel\Res

[UserSettings]
ApplicationLogo=crystal.bmp
CompanyName= IFCA Hotel
CompanyAddress1=Damansara Utama
CompanyAddress2=Petaling Jaya, Malaysia
CompanyAddress3=Tel. No.:

[SystemIntegration]
ConnectToAccount=0


