[Database]
Vendors=ODBC
DBMS=SYBASE
ServerName=IFCA_PNTS
Database=ifca1
UserID=MGR
DatabasePassword=
LogId=MGR
LogPassword=
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
DbParm=release='4.2'
AutoCommit=FALSE
AutoQuote=1
Columns=8
Lock=

[Application]
Idletime=0
custlogo=bv.bmp

[Security]
BmpBrowser=d:\res\*.bmp
WavBrowser=d:\res\*.wav
RowCount=l
//Bmp Brower=
//Wav Brower=d:\ifca\res\*.wav
//BmpBrower=d:\ifca\res\*.bmp

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
//Log On Fail=p2.wav
//Log On Successfully=chimes.wav
//Sound Enable=0

[Color]
Frame_Back=16777215
Sheet_Back=15138815
Sheet_Text=0
Err_Text=16711747
Err_Back=13500285
Err_TextBack=14811135
Warn_Text=8388608
Warn_Back=8421504
Warn_TextBack=15138815
//Error Message Background=0
//Error Message Text=255
//Error Message Text Background=15269887
//Frame Background=15269887
//Sheet Background=8454143
//Sheet Text=0
//Warning Message Background=0
//Warning Message Text=0
//Warning Message Text Background=15269887

//[App]
//Idle Time=1
//IdleTime=0
