[Database]
Vendors=ODBC
DBMS=MSS
ServerName=IFCA_nt003
Database=dproject
UserID=MGR
DatabasePassword=
LogId=MGR
LogPassword=
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
;DbParm=release='4.2'
AutoCommit=true
Lock=

[Application]
Idletime=0
custlogo=bv.bmp

[Security]
BmpBrowser=f:\res\*.bmp
WavBrowser=f:\res\*.wav
RowCount=l
//Bmp Brower=
//Wav Brower=d:\ifca\res\*.wav
//BmpBrower=d:\ifca\res\*.bmp
PicBrowser=
license=ÈÔÓÍ€ˇ‰„ﬂ

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
//Log On Fail=p2.wav
//Log On Successfully=chimes.wav
//Sound Enable=0

[Color]
Frame_Back=16777215
Sheet_Back=15466495
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
//Error Message Background=0
//Error Message Text=255
//Error Message Text Background=15269887
//Frame Background=15269887
//Sheet Background=8454143
//Sheet Text=0
//Warning Message Background=0
//Warning Message Text=0
//Warning Message Text Background=15269887

//[App]
//Idle Time=1
//IdleTime=0
Dw_Back=12632256
Column_Back=16777215
