[Database]
// Vendors=ODBC
DBMS=MSS
//serverName=sonline2_nt
serverName=hotel_nt
//dataBase=dproject22
//DataBase=dproject23
//DataBase=dproject4
//DataBase=Hohup_dat
//DataBase=dproj_2
//serverName=nt_server
dataBase=dproj_1

///////////////////////   SPA
//serverName=iims_nt
//DataBase=spa
////////////////////////

//servername=club_nt
//database=dproj_3

//ServerName=hotel_nt
//DataBase=daccount_bintang

//ServerName=dm_vincent
//database=bumimex

//ServerName=ilham_nt
//database=dproj22

//serverName=nt_server
//dataBase=dproj_5

//ServerName=club_nt
//database=dproj_3

//ServerName=account_nt
//database=purchase_db
//Database=sw_online_db

//ServerName=default_nt
//database=default_db
//database=dproj23_demo

//ServerName=ifca_nt
//DataBase=dproject

//serverName=RND1_NT
//DataBase=dproj_client

//serverName=document_nt
//DataBase=shukri

UserID=MGR
DatabasePassword=MGR
LogId=MGR
LogPassword=MGR
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
;DbParm=release='4.2'
AutoCommit=True
Lock=

[Application]
PostZoom=84
Idletime=0
dateformat=dd/mm/yyyy
custlogo=c:\res\ifca.bmp
custcompany=IFCA Consulting Sdn. Bhd.
custaddress1=25 Jalan SS20/11, Damansara Utama, Petaling Jaya Selangor
SetDefaultLanguage=Y
DefaultAccess=N
projectusage=N
Batchlimit=150
Admfees='FA'
Insfees='INS'
Ridingfee='RA'
Entryfees='FE'
Fine='FI'
BredComm='LB'
MRAFund=
MRAAdm=
SycesComm='SC'
WinningComm='WC'
WinningJockey='WJ'
WinningManager='WM'
WinningTrainer='WT'
country='malaysia'

[Security]
BmpBrowser=c:\res\*.bmp
WavBrowser=c:\res\*.wav
RowCount=l
PicBrowser=

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
Log On Fail=p2.wav
Log On Successfully=chimes.wav
Sound Enable=0

[Color]
Frame_Back=16777215
Sheet_Back=15466495
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
Dw_Back=12632256
Column_Back=16777215


[sonline2_nt]
//dproject
//license=6CMAN42-1273
//dproject22
//license=6XGR41F-1273
//dproject23
license=6ZJE2CE-0817
//dproject4
//license=6RP5XG9-1273
//dclub
//license=DWPMQ79B-1273
//dclub2
//license=DRHT6ZJ8-1273
//dclub3
//license=DHKX4HT3-1273

[club_nt]
//[club_nt dproj_5]
//license=1EJ121A5-065435
//[club_nt dproj_4]
//license=1ED6191C-065435
//[club_nt dproj_3]
//license=1ZVGRMLT-065435
//[club_nt dproj_3]
license=1ZVGRMLT-434875
//[club_nt dproj_2]
//license=1B91MAB5-065435
//[club_nt dproj_1]
//license=1HJ3J61T-065435
//dclub_d1
//license=3ZPBLQJ-7296139 
//dclub_d2
//license=3ETNBTZ-7296139
//dclub_d3
//license=3TAF4CJ-7296139
//dclub_d4
//license=V9GXTHE-7296139
//dclub_d5
//license=VDM9NMA-7296139

[account_nt]
//[account_nt purchase_db]
//license=D2AQNRD2-939299
//[sw_online_db]
//LICENSE=OCR5RJ3-939299

[default_nt]
//default_db
//license=31N1519-88497
//dproj23_demo
//license=DAJKJDPR-19041

//[hotel_nt]
//dproject2
//license=GCA57JRQ-75589

//[iimsnt]
license=EHHQZPZ-5512

[dm_vincent]
//license=MVRHHN34-056858

[RND1_NT]
//license=T2OT2LL-48361315

[ilham_nt]
//license=GD18ZCM7-230768

[document_nt]
//license=MZHKG7C9-9777

[hotel_nt]
//license=MXZDVHD1-057354
//license=DXT2JW3X-714
license=MXZDWBJC-057354
//license=GCA57JRQ-75589
//license=MHNRXP2A-714

[iims_nt]
license=QA7NQ5P-81781

[nt_server]
//dproj_1
license=1HKVRWPC-3798037
//dproj_2
//license=1HBKBHT5-3798037
//dproj_3
//icense=1BKBXT28-3798037
//dproj_4
//license=1ZZVH3NC-3798037
//dproj_5
//license=1E8KERF5-3798037
//dproj_6
//license=1EHWKCHZ-3798037
