[Database]
DBMS=MSS
ServerName=ifca_project
Database=dproject2
UserID=MGR
DatabasePassword=MGR
LogId=MGR
LogPassword=MGR
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
;DbParm=release='4.2'
AutoCommit=True
Lock=

[Application]
Idletime=0
custlogo=ifca.bmp
custcompany=
maxuserlicense=ιώξλήπβή

[Security]
BmpBrowser=*.bmp
WavBrowser=*.wav
RowCount=l
PicBrowser=
license=κÿπκάλεΰυ

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav

[Color]
Frame_Back=16777215
Sheet_Back=15466495
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
Dw_Back=12632256
Column_Back=16777215

