[Database]
DBMS=MSS
serverName=iims_nt
DataBase=spa
UserID=MGR
DatabasePassword=MGR
LogId=SPA
LogPassword=MGR
;DbParm=Connectstring='DSN=NTWS-IFCA',Disablebind=1,sqlcache=0
;DbParm=release='4.2'
AutoCommit=True
Lock=

[Application]
PostZoom=84
Idletime=0
dateformat=dd/mm/yyyy
custlogo=c:\res\ifca.bmp
custcompany=IFCA Consulting Sdn. Bhd.
custaddress1=25 Jalan SS20/11, Damansara Utama, Petaling Jaya Selangor
SetDefaultLanguage=Y
DefaultAccess=N
projectusage=N
Batchlimit=150
Admfees='FA'
Insfees='INS'
Ridingfee='RA'
Entryfees='FE'
Fine='FI'
BredComm='LB'
MRAFund=
MRAAdm=
SycesComm='SC'
WinningComm='WC'
WinningJockey='WJ'
WinningManager='WM'
WinningTrainer='WT'
country='malaysia'

[Security]
BmpBrowser=c:\res\*.bmp
WavBrowser=c:\res\*.wav
RowCount=l
PicBrowser=

[Sound]
Enable=0
AppOpen=tada.wav
Logonok=chimes.wav
Logonfail=p2.wav
AppClose=adios.wav
Application Close=adios.wav
Application Open=tada.wav
Log On Fail=p2.wav
Log On Successfully=chimes.wav
Sound Enable=0

[Color]
Frame_Back=16777215
Sheet_Back=15466495
Sheet_Text=0
Err_Text=0
Err_Back=255
Err_TextBack=12845055
Warn_Text=0
Warn_Back=8388608
Warn_TextBack=12845055
Dw_Back=12632256
Column_Back=16777215

[iims_nt]
license=QA7NQ5P-81781